tasks:
services:
    redis:
        name: redis
        description: Redis Server
        commands:
            start: sudo service redis-server start
            stop: sudo service redis-server stop
        triggeredBy:
            - postEnvironmentStart
